<a href="https://colab.research.google.com/github/ManJ-PC/Py/blob/master/FreeCodeCamp.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

In [ ]:
n = 3

In [ ]:
2 **3

SyntaxError: ignored

In [ ]:
120

120

In [ ]:
2**32

4294967296

In [ ]:
x = 5

In [ ]:
np.int8

numpy.int8

In [ ]:
np.int8

numpy.int8

So there is no access to the high performance, low level ... instructions with NumPy that changes because when you create an array NumPy, when you create these three element,

In [ ]:
import sys 
import numpy as np


np.array([1,2,3,4])

array([1, 2, 3, 4])

In [ ]:
a = np.array([1,2,3,4])
b= np.array([0, .5,  1,1.5,2])

In [ ]:
a[0], a[1]

(1, 2)

In [ ]:
a[0:]

array([1, 2, 3, 4])

In [ ]:
a[1:3]

array([2, 3])

In [ ]:
a[1:-1] # negative and ... steps works similar way of lists

array([2, 3])

In [ ]:
a[::2]

array([1, 3])

In [ ]:
b

array([0. , 0.5, 1. , 1.5, 2. ])

In [ ]:
b[0],b[2], b[-1]

(0.0, 1.0, 2.0)

In [ ]:
#NumPy is first immutable variable

In [ ]:
import numpy as np

In [ ]:
a = np.arange(4)

In [ ]:
a >= 2

array([False, False,  True,  True])

In [ ]:
a[a >= 2] 

array([2, 3])

In [ ]:
a.mean()

1.5

In [ ]:
a[~(a > a.mean())] # boolean operators return booleans arrays ...

array([0, 1])

## Difference in sizes between NumPy and Python
### and in terms of performance between them.

A regular number ... total size is 28 byte

# Extremely space consuming writes, not very efficient


In [ ]:
import sys
import numpy as np

# An integer in Python is > 24 bytes
sys.getsizeof(1)

28

In [ ]:
# Longs are even larger
sys.getsizeof(10**100)

72

In [ ]:
# Numpy size is much smaller
np.dtype(int).itemsize

8

In [ ]:
# Numpy size is much smaller
np.dtype(np.int8).itemsize

1

In [ ]:
np.dtype(float).itemsize

8

### **List are even larger**

In [ ]:
# A one-element list
sys.getsizeof([1])

80

In [ ]:
# An array of one element in numpy
np.array([1]).nbytes

8

### **And performance is also important**

In [ ]:
l = list(range(1000))

In [ ]:
a = np.arange(1000)

In [ ]:
%time np.sum(a**2)

CPU times: user 486 µs, sys: 0 ns, total: 486 µs
Wall time: 789 µs


332833500

In [ ]:
%time sum([x ** 2 for x in l])

CPU times: user 268 µs, sys: 31 µs, total: 299 µs
Wall time: 303 µs


332833500

In [ ]:
l1 = list(range(100000))

In [ ]:
a1 = np.arange(100000)

In [ ]:
%time np.sum(a1**2)

CPU times: user 612 µs, sys: 71 µs, total: 683 µs
Wall time: 696 µs


333328333350000

In [ ]:
%time sum([x ** 2 for x in l1])

CPU times: user 36.3 ms, sys: 673 µs, total: 36.9 ms
Wall time: 39.3 ms


333328333350000

### NumPy extremely faster compare with Python

### Useful Numpy functions



**random**

In [ ]:
np.random.random(size=2)

array([0.03749154, 0.99778056])

In [ ]:
np.random.normal(size=2)

array([-0.17900036,  1.37552063])

In [ ]:
np.random.rand(2, 4)

array([[0.7708725 , 0.51082991, 0.66717051, 0.38107535],
       [0.25643013, 0.9365987 , 0.94712408, 0.29034658]])

## Python in under 10 minutes - Exercises

[Link de Exercícios](https://github.com/ine-rmotr-curriculum/ds-content-python-under-10-minutes/blob/master/Exercises.ipynb)

### Exercise 1
Convert the following  ***str*** into ***int*** type



In [ ]:
revenue_as_string = "500000"

type(int(revenue_as_string))

int

### Exercise 2

Make a function using the following formula:

                    f(x,y) = 2x + y

In [ ]:
def function(x,y):
  return 2*x + y

In [ ]:
function(8,3)

19

In [ ]:
print(function(10,5))
function(-3, 10)

25


4

### Exercise 3
Make a function that receives a string as parameter and return the last letter on it.

In [ ]:
def lastletter(stext):
  size = len(stext)
  return stext[size-1]

In [ ]:
# def lastletter(stext):
#   for i in range(0, len(stext)):
#     return 

print(lastletter('Cowboiada.'))
lastletter('RMOTR')

.


'R'

In [ ]:
def last_letter(string):
  return string[-1]

In [ ]:
last_letter("cowboiada.")

'.'

### Exercise 4

Make a function that receives a list as parameter and return how manu elements it has; if it doesn't have any element return an error.

In [ ]:
lista = []
len(lista)

0

In [ ]:
prices = {'apple': 0.40, 'orange': 0.35, 'banana': 0.25}
for key in prices.keys(): # RuntimeError: dictionary changed size during iteration
  if key == 'orange':
    del prices['apple']

for key in list(prices.keys()):  # Use a list instead of a view 
  if key == 'orange':
    del prices[key] # Delete a key from prices

prices

{'apple': 0.4, 'banana': 0.25}

In [ ]:
type(str(14))

str

In [6]:
def ctdelement(* elems):
  if len(* elems) == 0:
    print('Error')
  return len(* elems) #elems dá 1, que é a própria lista!

In [10]:
#ctdelement 
ctdelement([8,4,3,2])
# ctdelement() # TypeError: len() takes exactly one argument (0 given)
ctdelement([]) # 0

Error


0

In [11]:
# Solution

def list_size(my_list):
  size = len(my_list)

  if (size > 0):
    return 'List has {} elements'.format(size)
  else:
    return 'Error, no elements'
    # sem return value ...

In [12]:
list_size([1,2,3])

'LIst has 3 elements'

# 2nd Set of exercises

[Lista de Exercícios](https://github.com/ine-rmotr-curriculum/freecodecamp-intro-to-numpy/blob/master/3.%20NumPy%20exercises.ipynb)

In [ ]:
num